# Import the relevant libraries

In [1]:
import numpy as np

# Declaring Scalars, Vectors and Matrices

## Scalars

In [2]:
s = 5

In [3]:
s

5

## Vectors

In [4]:
v = np.array([5,-2,4])
v

array([ 5, -2,  4])

## Matrices

In [5]:
m = np.array([[5, 12, 6], [-3, 0, 14]])

In [6]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

## Data Types

In [7]:
type(s)

int

In [8]:
type(v)

numpy.ndarray

In [9]:
type(m)

numpy.ndarray

In [10]:
s_array = np.array([5])
type(s_array)

numpy.ndarray

## Data Shape

In [11]:
m.shape

(2, 3)

In [12]:
v.shape

(3,)

## Creating a column vector

In [13]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [14]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [15]:
s_array.shape

(1,)